# Generated by Django 6.0.2 on 2026-02-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='movie_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_as_b', to='core.movie'),
        ),
    ]
